export const radioData = {
  name: "Rádio Sinta",
  domain: "radiosinta.com.br",
  iframeUrl: "https://livemus.com.br/player_barra_moderno/index.php?porta=28118",
  phoneRaw: "",
  phoneFormatted: "",
  whatsappLink: "https://wa.me/",
  instagramLink: "https://www.instagram.com/radiosinta",
  mailLink: "mailto:radiosinta@gmail.com",
  slogan: "Sinta a presença de Deus",
  pixKey: "radiosinta@gmail.com",
  pixHolder: "Caixa Econômica Federal",
  nowPlaying: "Rádio Sinta",
  credits: {
    text: "Desenvolvido por Douglas Borges - Smart Local",
    url: "https://smartlocal.com.br",
  },
  nav: [
    { label: "Início", href: "#inicio" },
    { label: "Programação", href: "#essencia" },
    { label: "Sintonize", href: "#sintonize" },
    { label: "Apoie", href: "#semeadores" },
  ],
  artists: [
    "Bruna Karla",
    "Fernandinho",
    "Aline Barros",
    "Gabriela Rocha",
    "Isaias Saad",
    "Morada",
    "Leandro Borges",
    "Anderson Freire",
    "Kemuel",
    "Adoração Central",
    "Thalles Roberto",
    "Preto no Branco",
  ],
} as const;

export type RadioData = typeof radioData;
